version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: kiran
      POSTGRES_PASSWORD: kiran0612
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

  python_server:
    build: ./app
    container_name: python_server
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python /app/server.py

volumes:
  my_postgres_data:
